name: churn-imbalanced-dataset
on: [push]
permissions: write-all
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout the code
        uses: actions/checkout@v3
      -
        name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      -
        name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      -
        name: setup cml
        uses: iterative/setup-cml@v1
      -
        name: Prepare Environment and Run the script.
        run: |
          # Your ML workflow goes here
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python "01- ML Exp with CML Tool/script.py"
      -
        name: Generate Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the report
          echo "## Metrics" > report.md
          # cat metrics.txt >> report.md
          awk 'NR%4{print "    " $0}{print ""}' metrics.txt >> report.md
          echo "## Confusion Matrix" >> report.md
          echo "![](./conf_matrix.png)" >> report.md
          cml comment create report.md
